Class {
	#name : #FamixGTEJavaIndexedFileAnchor,
	#superclass : #FamixGTEJavaSourceAnchor,
	#traits : 'FamixGTETIndexedFileNavigation',
	#classTraits : 'FamixGTETIndexedFileNavigation classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaIndexedFileAnchor class >> annotation [

	<FMClass: #IndexedFileAnchor super: #FamixGTEJavaSourceAnchor>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
