Class {
	#name : #FamixGTEJavaUnknownSourceLanguage,
	#superclass : #FamixGTEJavaSourceLanguage,
	#traits : 'FamixGTETUnknownSourceLanguage',
	#classTraits : 'FamixGTETUnknownSourceLanguage classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixGTEJavaSourceLanguage>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
