Class {
	#name : #FamixGTEJavaParameterType,
	#superclass : #FamixGTEJavaType,
	#traits : 'FamixGTETParameterType',
	#classTraits : 'FamixGTETParameterType classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaParameterType class >> annotation [

	<FMClass: #ParameterType super: #FamixGTEJavaType>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
