Class {
	#name : #FamixGTEJavaGlobalVariable,
	#superclass : #FamixGTEJavaNamedEntity,
	#traits : 'FamixGTETGlobalVariable',
	#classTraits : 'FamixGTETGlobalVariable classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaGlobalVariable class >> annotation [

	<FMClass: #GlobalVariable super: #FamixGTEJavaNamedEntity>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
