Class {
	#name : #FamixGTEJavaSourceAnchor,
	#superclass : #FamixGTEJavaEntity,
	#traits : 'FamixGTETSourceAnchor',
	#classTraits : 'FamixGTETSourceAnchor classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaSourceAnchor class >> annotation [

	<FMClass: #SourceAnchor super: #FamixGTEJavaEntity>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
