Class {
	#name : #FamixGTEJavaImplicitVariable,
	#superclass : #FamixGTEJavaNamedEntity,
	#traits : 'FamixGTETImplicitVariable',
	#classTraits : 'FamixGTETImplicitVariable classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaImplicitVariable class >> annotation [

	<FMClass: #ImplicitVariable super: #FamixGTEJavaNamedEntity>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
