Class {
	#name : #FamixGTEJavaThrownException,
	#superclass : #FamixGTEJavaException,
	#traits : 'FamixGTETThrownException',
	#classTraits : 'FamixGTETThrownException classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaThrownException class >> annotation [

	<FMClass: #ThrownException super: #FamixGTEJavaException>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
