Class {
	#name : #FamixGTEJavaModel,
	#superclass : #GraphooseModel,
	#category : #'Graphoose-Java-Entities-Model'
}

{ #category : #accessing }
FamixGTEJavaModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Graphoose-Traits' #'Graphoose-Query')
]

{ #category : #meta }
FamixGTEJavaModel class >> annotation [
	<FMClass: #FamixGTEJavaModel super: #MooseModel>
	<package: #'Graphoose-Java-Entities'>
	<generated>
]
