Class {
	#name : #FamixGTEJavaImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'Graphoose-Java-Entities'
}

{ #category : #testing }
FamixGTEJavaImportingContext >> importAccess [
	<generated>
	^ self import: FamixGTEJavaAccess
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importAnnotationInstance [
	<generated>
	^ self import: FamixGTEJavaAnnotationInstance
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importAnnotationInstanceAttribute [
	<generated>
	^ self import: FamixGTEJavaAnnotationInstanceAttribute
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importAnnotationType [
	<generated>
	^ self import: FamixGTEJavaAnnotationType
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importAnnotationTypeAttribute [
	<generated>
	^ self import: FamixGTEJavaAnnotationTypeAttribute
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importAttribute [
	<generated>
	^ self import: FamixGTEJavaAttribute
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importCaughtException [
	<generated>
	^ self import: FamixGTEJavaCaughtException
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importClass [
	<generated>
	^ self import: FamixGTEJavaClass
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importComment [
	<generated>
	^ self import: FamixGTEJavaComment
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importContainerEntity [
	<generated>
	^ self import: FamixGTEJavaContainerEntity
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importDeclaredException [
	<generated>
	^ self import: FamixGTEJavaDeclaredException
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importEntity [
	<generated>
	^ self import: FamixGTEJavaEntity
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importEnum [
	<generated>
	^ self import: FamixGTEJavaEnum
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importEnumValue [
	<generated>
	^ self import: FamixGTEJavaEnumValue
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importException [
	<generated>
	^ self import: FamixGTEJavaException
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importFile [
	<generated>
	^ self import: FamixGTEJavaFile
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importFolder [
	<generated>
	^ self import: FamixGTEJavaFolder
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importGlobalVariable [
	<generated>
	^ self import: FamixGTEJavaGlobalVariable
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importImplicitVariable [
	<generated>
	^ self import: FamixGTEJavaImplicitVariable
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importIndexedFileAnchor [
	<generated>
	^ self import: FamixGTEJavaIndexedFileAnchor
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importInheritance [
	<generated>
	^ self import: FamixGTEJavaInheritance
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importInvocation [
	<generated>
	^ self import: FamixGTEJavaInvocation
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importLocalVariable [
	<generated>
	^ self import: FamixGTEJavaLocalVariable
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importMethod [
	<generated>
	^ self import: FamixGTEJavaMethod
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importNamedEntity [
	<generated>
	^ self import: FamixGTEJavaNamedEntity
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importNamespace [
	<generated>
	^ self import: FamixGTEJavaNamespace
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importPackage [
	<generated>
	^ self import: FamixGTEJavaPackage
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importParameter [
	<generated>
	^ self import: FamixGTEJavaParameter
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importParameterType [
	<generated>
	^ self import: FamixGTEJavaParameterType
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importParameterizableClass [
	<generated>
	^ self import: FamixGTEJavaParameterizableClass
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importParameterizedType [
	<generated>
	^ self import: FamixGTEJavaParameterizedType
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importPrimitiveType [
	<generated>
	^ self import: FamixGTEJavaPrimitiveType
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importReference [
	<generated>
	^ self import: FamixGTEJavaReference
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importSourceAnchor [
	<generated>
	^ self import: FamixGTEJavaSourceAnchor
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importSourceLanguage [
	<generated>
	^ self import: FamixGTEJavaSourceLanguage
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importSourceTextAnchor [
	<generated>
	^ self import: FamixGTEJavaSourceTextAnchor
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importSourcedEntity [
	<generated>
	^ self import: FamixGTEJavaSourcedEntity
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importThrownException [
	<generated>
	^ self import: FamixGTEJavaThrownException
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importType [
	<generated>
	^ self import: FamixGTEJavaType
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importUnknownSourceLanguage [
	<generated>
	^ self import: FamixGTEJavaUnknownSourceLanguage
]

{ #category : #testing }
FamixGTEJavaImportingContext >> importUnknownVariable [
	<generated>
	^ self import: FamixGTEJavaUnknownVariable
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportAccess [
	<generated>
	^ self shouldImport: FamixGTEJavaAccess
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportAnnotationInstance [
	<generated>
	^ self shouldImport: FamixGTEJavaAnnotationInstance
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportAnnotationInstanceAttribute [
	<generated>
	^ self shouldImport: FamixGTEJavaAnnotationInstanceAttribute
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportAnnotationType [
	<generated>
	^ self shouldImport: FamixGTEJavaAnnotationType
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportAnnotationTypeAttribute [
	<generated>
	^ self shouldImport: FamixGTEJavaAnnotationTypeAttribute
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportAttribute [
	<generated>
	^ self shouldImport: FamixGTEJavaAttribute
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportCaughtException [
	<generated>
	^ self shouldImport: FamixGTEJavaCaughtException
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportClass [
	<generated>
	^ self shouldImport: FamixGTEJavaClass
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportComment [
	<generated>
	^ self shouldImport: FamixGTEJavaComment
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportContainerEntity [
	<generated>
	^ self shouldImport: FamixGTEJavaContainerEntity
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportDeclaredException [
	<generated>
	^ self shouldImport: FamixGTEJavaDeclaredException
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportEntity [
	<generated>
	^ self shouldImport: FamixGTEJavaEntity
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportEnum [
	<generated>
	^ self shouldImport: FamixGTEJavaEnum
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportEnumValue [
	<generated>
	^ self shouldImport: FamixGTEJavaEnumValue
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportException [
	<generated>
	^ self shouldImport: FamixGTEJavaException
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportFile [
	<generated>
	^ self shouldImport: FamixGTEJavaFile
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportFolder [
	<generated>
	^ self shouldImport: FamixGTEJavaFolder
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportGlobalVariable [
	<generated>
	^ self shouldImport: FamixGTEJavaGlobalVariable
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportImplicitVariable [
	<generated>
	^ self shouldImport: FamixGTEJavaImplicitVariable
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportIndexedFileAnchor [
	<generated>
	^ self shouldImport: FamixGTEJavaIndexedFileAnchor
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportInheritance [
	<generated>
	^ self shouldImport: FamixGTEJavaInheritance
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportInvocation [
	<generated>
	^ self shouldImport: FamixGTEJavaInvocation
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportLocalVariable [
	<generated>
	^ self shouldImport: FamixGTEJavaLocalVariable
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportMethod [
	<generated>
	^ self shouldImport: FamixGTEJavaMethod
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportNamedEntity [
	<generated>
	^ self shouldImport: FamixGTEJavaNamedEntity
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportNamespace [
	<generated>
	^ self shouldImport: FamixGTEJavaNamespace
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportPackage [
	<generated>
	^ self shouldImport: FamixGTEJavaPackage
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportParameter [
	<generated>
	^ self shouldImport: FamixGTEJavaParameter
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportParameterType [
	<generated>
	^ self shouldImport: FamixGTEJavaParameterType
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportParameterizableClass [
	<generated>
	^ self shouldImport: FamixGTEJavaParameterizableClass
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportParameterizedType [
	<generated>
	^ self shouldImport: FamixGTEJavaParameterizedType
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportPrimitiveType [
	<generated>
	^ self shouldImport: FamixGTEJavaPrimitiveType
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportReference [
	<generated>
	^ self shouldImport: FamixGTEJavaReference
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportSourceAnchor [
	<generated>
	^ self shouldImport: FamixGTEJavaSourceAnchor
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportSourceLanguage [
	<generated>
	^ self shouldImport: FamixGTEJavaSourceLanguage
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportSourceTextAnchor [
	<generated>
	^ self shouldImport: FamixGTEJavaSourceTextAnchor
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportSourcedEntity [
	<generated>
	^ self shouldImport: FamixGTEJavaSourcedEntity
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportThrownException [
	<generated>
	^ self shouldImport: FamixGTEJavaThrownException
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportType [
	<generated>
	^ self shouldImport: FamixGTEJavaType
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportUnknownSourceLanguage [
	<generated>
	^ self shouldImport: FamixGTEJavaUnknownSourceLanguage
]

{ #category : #testing }
FamixGTEJavaImportingContext >> shouldImportUnknownVariable [
	<generated>
	^ self shouldImport: FamixGTEJavaUnknownVariable
]
