Class {
	#name : #FamixGTEJavaInheritance,
	#superclass : #FamixGTEJavaEntity,
	#traits : 'FamixGTETInheritance',
	#classTraits : 'FamixGTETInheritance classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaInheritance class >> annotation [

	<FMClass: #Inheritance super: #FamixGTEJavaEntity>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
