Class {
	#name : #FamixGTEJavaCaughtException,
	#superclass : #FamixGTEJavaException,
	#traits : 'FamixGTETCaughtException',
	#classTraits : 'FamixGTETCaughtException classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaCaughtException class >> annotation [

	<FMClass: #CaughtException super: #FamixGTEJavaException>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
