Class {
	#name : #FamixGTEJavaSourceLanguage,
	#superclass : #FamixGTEJavaEntity,
	#traits : 'FamixGTETSourceLanguage',
	#classTraits : 'FamixGTETSourceLanguage classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaSourceLanguage class >> annotation [

	<FMClass: #SourceLanguage super: #FamixGTEJavaEntity>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
