Class {
	#name : #FamixGTEJavaFolder,
	#superclass : #FamixGTEJavaNamedEntity,
	#traits : 'FamixGTETFolder',
	#classTraits : 'FamixGTETFolder classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaFolder class >> annotation [

	<FMClass: #Folder super: #FamixGTEJavaNamedEntity>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
