Class {
	#name : #FamixGTEJavaReference,
	#superclass : #FamixGTEJavaEntity,
	#traits : 'FamixGTETReference',
	#classTraits : 'FamixGTETReference classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaReference class >> annotation [

	<FMClass: #Reference super: #FamixGTEJavaEntity>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
