Class {
	#name : #FamixGTEJavaParameterizableClass,
	#superclass : #FamixGTEJavaClass,
	#traits : 'FamixGTETWithParameterizedTypes',
	#classTraits : 'FamixGTETWithParameterizedTypes classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaParameterizableClass class >> annotation [

	<FMClass: #ParameterizableClass super: #FamixGTEJavaClass>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
