Class {
	#name : #FamixGTEJavaDeclaredException,
	#superclass : #FamixGTEJavaException,
	#traits : 'FamixGTETDeclaredException',
	#classTraits : 'FamixGTETDeclaredException classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaDeclaredException class >> annotation [

	<FMClass: #DeclaredException super: #FamixGTEJavaException>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
