Class {
	#name : #FamixGTEJavaSourceTextAnchor,
	#superclass : #FamixGTEJavaSourceAnchor,
	#traits : 'FamixGTETHasImmediateSource',
	#classTraits : 'FamixGTETHasImmediateSource classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixGTEJavaSourceAnchor>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
