Class {
	#name : #FamixGTEJavaComment,
	#superclass : #FamixGTEJavaSourcedEntity,
	#traits : 'FamixGTETComment',
	#classTraits : 'FamixGTETComment classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaComment class >> annotation [

	<FMClass: #Comment super: #FamixGTEJavaSourcedEntity>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
