Class {
	#name : #FamixGTEJavaException,
	#superclass : #FamixGTEJavaEntity,
	#traits : 'FamixGTETException',
	#classTraits : 'FamixGTETException classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaException class >> annotation [

	<FMClass: #Exception super: #FamixGTEJavaEntity>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
