Class {
	#name : #FamixGTEJavaMethod,
	#superclass : #FamixGTEJavaContainerEntity,
	#traits : 'FamixGTETCanBeAbstract + FamixGTETCanBeFinal + FamixGTETHasVisibility + FamixGTETMethod + FamixGTETWithCaughtExceptions + FamixGTETWithDeclaredExceptions + FamixGTETWithThrownExceptions',
	#classTraits : 'FamixGTETCanBeAbstract classTrait + FamixGTETCanBeFinal classTrait + FamixGTETHasVisibility classTrait + FamixGTETMethod classTrait + FamixGTETWithCaughtExceptions classTrait + FamixGTETWithDeclaredExceptions classTrait + FamixGTETWithThrownExceptions classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaMethod class >> annotation [

	<FMClass: #Method super: #FamixGTEJavaContainerEntity>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
