Class {
	#name : #FamixGTEJavaUnknownVariable,
	#superclass : #FamixGTEJavaNamedEntity,
	#traits : 'FamixGTETUnknownVariable',
	#classTraits : 'FamixGTETUnknownVariable classTrait',
	#category : #'Graphoose-Java-Entities-Entities'
}

{ #category : #meta }
FamixGTEJavaUnknownVariable class >> annotation [

	<FMClass: #UnknownVariable super: #FamixGTEJavaNamedEntity>
	<package: #'Graphoose-Java-Entities'>
	<generated>
	^self
]
